name: "SOC-003 | T1003.001 — LSASS Credential Dumping"
type: any
index: soc-logs-*
realert: { minutes: 1 }
filter:
  - bool:
      should:
        - bool:
            must:
              - term: { "EventID": "10" }
              - wildcard: { "TargetImage": "*lsass.exe" }
        - wildcard: { "CommandLine": "*sekurlsa*" }
        - wildcard: { "CommandLine": "*lsadump*" }
        - wildcard: { "CommandLine": "*mimikatz*" }
alert: ["post"]
http_post_url: "http://stackstorm:9101/v1/webhooks/elastalert"
http_post_payload:
  rule_id: "SOC-003"
  severity: "critical"
  mitre: "T1003.001"
