cluster.name: soc-cluster
network.host: 0.0.0.0
http.port: 9200
discovery.seed_hosts: ["opensearch-node1","opensearch-node2"]
cluster.initial_master_nodes: ["opensearch-node1","opensearch-node2"]
bootstrap.memory_lock: true
plugins.security.ssl.http.enabled: false
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.allow_unsafe_democertificates: true
plugins.security.allow_default_init_securityindex: true
plugins.security.audit.type: internal_opensearch
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.restapi.roles_enabled: ["all_access","security_rest_api_access"]
